[workspace]
members = [
    "bin/app",
    "bin/libs/config",
    "bin/libs/error",
    "bin/libs/internal",

    "libs/config",
    "libs/error",
    "libs/io",
    "libs/pbo",
    "libs/preprocessor",
    "libs/signing",
    "libs/tokens",
    "libs/version",
]

[workspace.dependencies]
pest = "2.5.2"
pest_derive = "2.5.2"
clap = "4.0.32"
serde = { version = "1.0.152", features = ["derive"] }
sha-1 = "0.10.1"
