[workspace]
members = [
    "bin/app",
    "bin/libs/config",
    "bin/libs/error",
    "bin/libs/internal",
    "bin/libs/rhai",

    "libs/config",
    "libs/error",
    "libs/io",
    "libs/pbo",
    "libs/preprocessor",
    "libs/signing",
    "libs/tokens",
    "libs/version",
]

[workspace.dependencies]
clap = "4.1.4"
colored = "2.0.0"
git2 = "0.16.1"
pest = "2.5.4"
pest_derive = "2.5.4"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sha-1 = "0.10.1"
toml = "0.6.0"
tracing = "0.1.37"
vfs = "0.9.0"
walkdir = "2.3.2"
zip = "0.6.3"
