[workspace]
members = [
    "bin/app",
    "bin/libs/internal",
    "bin/libs/project",

    "libs/config",
    "libs/error",
    "libs/io",
    "libs/pbo",
    "libs/preprocessor",
    "libs/tokens",
    "libs/signing",
]

[workspace.dependencies]
pest = "2.4.1"
pest_derive = "2.4.1"
clap = "4.0.20"
serde = { version = "1.0.147", features = ["derive"] }
