[workspace]
members = [
    "bin/app",
    "bin/libs/internal",
    "bin/libs/project",

    "libs/config",
    "libs/error",
    "libs/io",
    "libs/pbo",
    "libs/preprocessor",
    "libs/signing",
    "libs/tokens",
    "libs/version",
]

[workspace.dependencies]
pest = "2.5.1"
pest_derive = "2.5.1"
clap = "4.0.30"
serde = { version = "1.0.151", features = ["derive"] }
sha-1 = "0.10.1"
