[package]
name = "hemtt-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hemtt = { path = "../bin" }
hemtt-common = { path = "../libs/common" }

hemtt-config = { path = "../libs/config" }
hemtt-preprocessor = { path = "../libs/preprocessor" }

chumsky = "0.9.3"
dashmap = "5.5.3"
ropey = "1.6.1"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.35.1", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"]}
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", features = ["json"] }
url = "2.5.0"
vfs = { workspace = true }
