[package]
name = "hemtt"
description = "HEMTT - Arma 3 Build Tool"
version = "0.10.0"
edition = "2021"

[dependencies]
hemtt-error = { path = "../../libs/error" }
hemtt-bin-error = { path = "../libs/error"}

hemtt-bin-internal = { path = "../libs/internal" }
hemtt-bin-project = { path = "../libs/project" }

hemtt-config = { path = "../../libs/config" }
hemtt-pbo = { path = "../../libs/pbo" }
hemtt-preprocessor = { path = "../../libs/preprocessor" }
hemtt-tokens = { path = "../../libs/tokens" }
hemtt-signing = { path = "../../libs/signing" }

anyhow = "1.0.68"
atty = "0.2.14"
clap = { workspace = true }
dialoguer = "0.10.2"
fs_extra = "1.2.0"
git2 = "0.15.0"
glob = "0.3.0"
lazy_static = "1.4.0"
peekmore = "1.0.0"
rayon = "1.6.1"
rust-embed = "6.4.2"
steamlocate = { git = "https://github.com/LovecraftianHorror/steamlocate-rs/", branch = "fully-switch-from-steamy-vdf" }
time = "0.3.17"
vfs = "0.9.0"
zip = "0.6.3"

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
