[package]
name = "hemtt"
description = "HEMTT - Arma 3 Build Tool"
version = "0.10.0-rc1"
edition = "2021"

[dependencies]
hemtt-error = { path = "../../libs/error" }
hemtt-bin-error = { path = "../libs/error"}

hemtt-bin-internal = { path = "../libs/internal" }
hemtt-bin-config = { path = "../libs/config" }
hemtt-bin-rhai = { path = "../libs/rhai" }

hemtt-config = { path = "../../libs/config" }
hemtt-pbo = { path = "../../libs/pbo" }
hemtt-preprocessor = { path = "../../libs/preprocessor" }
hemtt-tokens = { path = "../../libs/tokens" }
hemtt-signing = { path = "../../libs/signing" }
hemtt-version = { path = "../../libs/version" }

ansi_term = "0.12.1"
anyhow = "1.0.69"
atty = "0.2.14"
clap = { workspace = true }
colored = { workspace = true }
dialoguer = "0.10.3"
fs_extra = "1.3.0"
git2 = { workspace = true }
glob = "0.3.1"
num_cpus = "1.15.0"
peekmore = { workspace = true }
rayon = "1.7.0"
rhai = "1.12.0"
rust-embed = "6.6.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
steamlocate = { git = "https://github.com/LovecraftianHorror/steamlocate-rs/", branch = "fully-switch-from-steamy-vdf" }
time = "0.3.20"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.16", features = ["json"] }
tracing-tracy = "0.10.2"
vfs = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.11.0"
