[package]
name = "hemtt"
description = "HEMTT - Arma 3 Build Tool"
version = "0.10.0"
edition = "2021"

[dependencies]
hemtt-error = { path = "../../libs/error" }

hemtt-bin-internal = { path = "../libs/internal" }
hemtt-bin-project = { path = "../libs/project" }

hemtt-config = { path = "../../libs/config" }
hemtt-pbo = { path = "../../libs/pbo" }
hemtt-preprocessor = { path = "../../libs/preprocessor" }

anyhow = "1.0.66"
clap = { workspace = true }
lazy_static = "1.4.0"
vfs = "0.7.1"
rayon = "1.5.3"

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
