name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nightly:
    name: nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: bench
      - run: cargo +nightly bench -- --output-format bencher | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: output.txt
          gh-repository: github.com/hemtt/bench
          github-token: ${{ secrets.PAGES_TOKEN }}
          auto-push: false
          comment-always: true
          gh-pages-branch: main
      - name: Push benchmark result
        if: github.event_name != 'pull_request'
        run: git push 'https://${{ secrets.PAGES_TOKEN }}@github.com/hemtt/bench.git' main:main
