name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - runner: ubuntu-latest
            name: ubuntu
            artifact: linux-x64
            exe: hemtt
          - runner: windows-latest
            name: windows
            artifact: windows-x64
            exe: hemtt.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
        with:
          key: build
      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os.artifact }}
          path: target/release/${{ matrix.os.exe }}

  mods:
    name:  ${{ matrix.os.name }} / ${{ matrix.mod.name }}
    runs-on: ${{ matrix.os.runner }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        os: 
          - runner: ubuntu-latest
            name: ubuntu
            artifact: linux-x64
          - runner: windows-latest
            name: windows
            artifact: windows-x64
        mod:
          - name: Advanced Combat Environment
            repo: acemod/ACE3
            path: ace3
            commit: d87e16e87ecf2db9429b19f5ac4cf06bab7aaad6
          - name: POTATO
            repo: BourbonWarfare/POTATO
            path: potato
            commit: fab121ce624b6656dd7afd2d29429aa762b28813
    steps:
      - name: Download HEMTT
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.os.artifact }}
          path: hemtt
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.mod.repo }}
          path: ${{ matrix.mod.path }}
          ref: ${{ matrix.mod.commit }}
      - name: Install Linux
        if: startsWith(matrix.os.runner, 'ubuntu')
        run: |
          cd hemtt && cp hemtt /usr/local/bin/hemtt && chmod +x /usr/local/bin/hemtt
      - name: Install Windows
        if: startsWith(matrix.os.runner, 'windows')
        run: |
          cd hemtt && copy hemtt.exe C:\Windows\System32\hemtt.exe
      - name: `hemtt dev` on ${{ matrix.mod.name }}
        run: |
          cd ${{ matrix.mod.path }} && hemtt dev
      - name: Install Arma 3 Tools
        if: startsWith(matrix.os.runner, 'windows')
        uses: arma-actions/arma3-tools@master
        with:
          toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}
      - name: `hemtt build` on ${{ matrix.mod.name }}
        run: |
          cd ${{ matrix.mod.path }} && hemtt build
